// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from encrypt.djinni

#pragma once

#include "data_processor.hpp"
#include "source_data.hpp"
#include "result_data.hpp"
#include "result_code.hpp"
#include "process_call_back.hpp"

namespace ifarseer {

    class SimpleDataProcessor final : public DataProcessor {
        public:
        virtual void process(const SourceData & data, const std::shared_ptr<ProcessCallBack> & callback) override {
            const ResultData result(result_code::OK, data.data, data.length);
            callback->on_result(result);
        }

        SimpleDataProcessor(){}
        ~SimpleDataProcessor(){}
    };

    std::shared_ptr<DataProcessor> DataProcessor::create() {
        return std::make_shared<SimpleDataProcessor>();
    }

}  // namespace ifarseer
